version: '3.8'

services:
  dev:
    container_name: nestjs_api_disruptiva
    image: nestjs-api-disruptiva:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile-dev
    command: npm run start:debug
    depends_on:
      - db
    ports:
      - 3051:3000
    networks:
      - nesjs-network-disruptiva
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      DB_NAME: disruptiva
      DB_HOST: db
      DB_USER: postgres
      DB_ROOT_PASSWORD: disruptivapass
      DB_PASSWORD: disruptivapass
      SECRET: disruptiva94658414
      DB_PORT: 5432
      ENV: env
      ADMIN_PASSWORD: disruptivapass
  db:
    image: postgres
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    ports:
      - '5431:5432'
    networks:
      - nesjs-network-disruptiva
    environment:
      POSTGRES_PASSWORD: disruptivapass
volumes:
  DB_data_disruptiva:
networks:
  nesjs-network-disruptiva:
